"""Initial migration: add usage tables

Revision ID: e43c4c7bd8c2
Revises:
Create Date: 2026-01-05 20:14:09.603809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e43c4c7bd8c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('total_model_call_count', sa.Integer(), nullable=False),
    sa.Column('total_tokens_usage', sa.Integer(), nullable=False),
    sa.Column('x_time_json', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_usage_total_model_call_count'), 'model_usage', ['total_model_call_count'], unique=False)
    op.create_index(op.f('ix_model_usage_total_tokens_usage'), 'model_usage', ['total_tokens_usage'], unique=False)
    op.create_table('quota_limit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('current_usage', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('usage_details_json', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quota_limit_percentage'), 'quota_limit', ['percentage'], unique=False)
    op.create_index(op.f('ix_quota_limit_type'), 'quota_limit', ['type'], unique=False)
    op.create_table('tool_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('total_network_search_count', sa.Integer(), nullable=False),
    sa.Column('total_web_read_mcp_count', sa.Integer(), nullable=False),
    sa.Column('total_zread_mcp_count', sa.Integer(), nullable=False),
    sa.Column('total_search_mcp_count', sa.Integer(), nullable=False),
    sa.Column('tool_details_json', sa.String(), nullable=False),
    sa.Column('x_time_json', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_usage')
    op.drop_index(op.f('ix_quota_limit_type'), table_name='quota_limit')
    op.drop_index(op.f('ix_quota_limit_percentage'), table_name='quota_limit')
    op.drop_table('quota_limit')
    op.drop_index(op.f('ix_model_usage_total_tokens_usage'), table_name='model_usage')
    op.drop_index(op.f('ix_model_usage_total_model_call_count'), table_name='model_usage')
    op.drop_table('model_usage')
    # ### end Alembic commands ###
